### ISSUE TITLE
Maintainership

### ISSUE THREAD

**Issue by amesgen** [monadfix/safe-wild-cards#2]
Just saw your [post on reddit](https://redd.it/1bchjdk) looking for maintainership; I would be open (I recently recommended it to a coworker, and then opened #1).

**Comment by neongreen** [comment]
@amesgen sorry for not getting back to you on this. If you're still up for it, email me your Hackage username & I'll add you to the maintainers group

**Comment by amesgen** [comment]
No problem! My Hackage username is `amesgen`. Also sent you an e-mail.

**Comment by amesgen** [comment]
Thanks!
